spring.application.name=app_novatech
server.port = 8082
# Configuracion de conexion a MySQL
spring.datasource.url=jdbc:mysql://localhost:3307/ecommerce_db?
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true